/*
 * korm
 *
 * Copyright (c) 2018, Michael Foidl
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package at.michaelfoidl.korm.core.runtime

import at.michaelfoidl.korm.core.io.IOOracle
import at.michaelfoidl.korm.interfaces.Database
import at.michaelfoidl.korm.interfaces.Migration
import org.jetbrains.exposed.sql.Table
import java.io.File
import kotlin.reflect.KClass

internal class ClassFetcher(
        private val rootFolder: File
) {
    // TODO work out concept for which files go where (migrations should be checked in, database implementations should probably not be checked in). Also, files generated by the tests should never be checked in.

    fun fetchTable(entityClass: KClass<*>, rootPackage: String): Table {
        return ClassLoader(this.rootFolder)
                .objectInstance<Table>(IOOracle.getTablePackage(rootPackage) + "." + IOOracle.getTableName(entityClass))!!
    }

    fun fetchMigration(databaseName: String, migrationPackage: String, version: Long): Migration {
        val migrationFileName: String = IOOracle.getMigrationFileName(databaseName, migrationPackage, version)
        return ClassLoader(this.rootFolder).createInstance<Migration>(migrationFileName)!!
    }

    inline fun <reified T : Database> fetchDatabase(databaseName: String, version: Long): T {
        val databaseFileName: String = IOOracle.getDatabaseFileName(databaseName, version)
        return ClassLoader(this.rootFolder).createInstance<T>(databaseFileName)!!
    }
}